# Copyright 2025 Greenmask
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  playground-dbs-filler:
    environment:
      TMP_DIR: "/tmp/schema"
      MYSQL_USER: root
      MYSQL_PWD: 1234
      ORIGINAL_DB_HOST: "playground-mysql-db-original"
      ORIGINAL_DB_NAME: "playground"
      ORIGINAL_DB_PORT: "3306"
    platform: linux/amd64
    build:
      context: docker/greenmask/mysql/filldb
    depends_on:
      playground-mysql-db-original:
        condition: service_started

  playground-mysql-storage:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ROOT_USER=Q3AM3UQ867SPQQA43P2F"
      - "MINIO_ROOT_PASSWORD=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/adventureworks && minio server /export --console-address :9001'
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 2

  playground-mysql-db-original:
    image: mysql:8.0
    container_name: mysql_playground_original
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: playground
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

  playground-mysql-db-transformed:
    image: mysql:8.0
    container_name: mysql_playground_transformed
    command: --local-infile=1
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: playground
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"

  greenmask:
    volumes:
      - ./playground/mysql:/var/lib/playground
    image: "greenmask/greenmask:mysql-8.0-latest"
    working_dir: /var/lib/playground
    environment:
      MYSQL_USER: root
      MYSQL_PWD: 1234
      ORIGINAL_DB_HOST: "playground-mysql-db-original"
      ORIGINAL_DB_NAME: "employees"
      ORIGINAL_DB_PORT: "3306"
      TRANSFORMED_DB_HOST: "playground-mysql-db-transformed"
      TRANSFORMED_DB_NAME: "employees"
      TRANSFORMED_DB_PORT: "3306"
      DATABASE_HOST: "playground-db"
    depends_on:
      #      playground-dbs-filler:
      #        condition: service_completed_successfully
      playground-mysql-storage:
        condition: service_healthy
      playground-mysql-db-original:
        condition: service_started
      playground-mysql-db-transformed:
        condition: service_started
    entrypoint: "/var/lib/playground/run.sh"

  greenmask-from-source:
    working_dir: /var/lib/playground
    volumes:
      - ./playground/mysql:/var/lib/playground
    build:
      dockerfile: docker/greenmask/mysql/main/Dockerfile
      context: ./
    platform: linux/amd64
    environment:
      MYSQL_USER: root
      MYSQL_PWD: 1234
      ORIGINAL_DB_HOST: "playground-mysql-db-original"
      ORIGINAL_DB_NAME: "employees"
      ORIGINAL_DB_PORT: "3306"
      TRANSFORMED_DB_HOST: "playground-mysql-db-transformed"
      TRANSFORMED_DB_NAME: "employees"
      TRANSFORMED_DB_PORT: "3306"
    depends_on:
      playground-mysql-storage:
        condition: service_healthy
      playground-mysql-db-original:
        condition: service_started
      playground-mysql-db-transformed:
        condition: service_started
    entrypoint: "/var/lib/playground/run.sh"
