site_name: Greenmask — PostgreSQL database anonymization and synthetic data generation tool

# Theme
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.indexes
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    #    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  #    - toc.follow
  palette:
    scheme: default
    primary: teal
    accent: indigo
    toggle:
      icon: material/brightness-7


# Markdown extensions
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - tables

nav:
  - Documentation:
      - Architecture: architecture.md
      - Playground: playground.md
      - Installation: installation.md
      - Configuration: configuration.md
      - Commands:
          - commands/index.md
          - list-transformers: commands/list-transformers.md
          - show-transformer: commands/show-transformer.md
          - validate: commands/validate.md
          - dump: commands/dump.md
          - list-dumps: commands/list-dumps.md
          - show-dump: commands/show-dump.md
          - restore: commands/restore.md
          - delete: commands/delete.md
      - Database subset: database_subset.md
      - Transformers:
          - built_in_transformers/index.md
          - Dynamic parameters: built_in_transformers/dynamic_parameters.md
          - Transformation engines: built_in_transformers/transformation_engines.md
          - Parameters templating: built_in_transformers/parameters_templating.md
          - Transformation conditions: built_in_transformers/transformation_condition.md
          - Transformation inheritance: built_in_transformers/transformation_inheritance.md
          - Standard transformers:
              - built_in_transformers/standard_transformers/index.md
              - Cmd: built_in_transformers/standard_transformers/cmd.md
              - Dict: built_in_transformers/standard_transformers/dict.md
              - Hash: built_in_transformers/standard_transformers/hash.md
              - Masking: built_in_transformers/standard_transformers/masking.md
              - NoiseDate: built_in_transformers/standard_transformers/noise_date.md
              - NoiseFloat: built_in_transformers/standard_transformers/noise_float.md
              - NoiseNumeric: built_in_transformers/standard_transformers/noise_numeric.md
              - NoiseInt: built_in_transformers/standard_transformers/noise_int.md
              - RandomBool: built_in_transformers/standard_transformers/random_bool.md
              - RandomChoice: built_in_transformers/standard_transformers/random_choice.md
              - RandomDate: built_in_transformers/standard_transformers/random_date.md
              - RandomFloat: built_in_transformers/standard_transformers/random_float.md
              - RandomNumeric: built_in_transformers/standard_transformers/random_numeric.md
              - RandomInt: built_in_transformers/standard_transformers/random_int.md
              - RandomString: built_in_transformers/standard_transformers/random_string.md
              - RandomUuid: built_in_transformers/standard_transformers/random_uuid.md
              - RandomLatitude: built_in_transformers/standard_transformers/random_latitude.md
              - RandomLongitude: built_in_transformers/standard_transformers/random_longitude.md
              - RandomUnixTimestamp: built_in_transformers/standard_transformers/random_unix_timestamp.md
              - RandomDayOfWeek: built_in_transformers/standard_transformers/random_day_of_week.md
              - RandomDayOfMonth: built_in_transformers/standard_transformers/random_day_of_month.md
              - RandomMonthName: built_in_transformers/standard_transformers/random_month_name.md
              - RandomYearString: built_in_transformers/standard_transformers/random_year_string.md
              - RandomCentury: built_in_transformers/standard_transformers/random_century.md
              - RandomCompany: built_in_transformers/standard_transformers/random_company.md
              - RandomTimezone: built_in_transformers/standard_transformers/random_timezone.md
              - RandomEmail: built_in_transformers/standard_transformers/random_email.md
              - RandomUsername: built_in_transformers/standard_transformers/random_username.md
              - RandomPassword: built_in_transformers/standard_transformers/random_password.md
              - RandomDomainName: built_in_transformers/standard_transformers/random_domain_name.md
              - RandomPerson: built_in_transformers/standard_transformers/random_person.md
              - RandomURL: built_in_transformers/standard_transformers/random_url.md
              - RandomMac: built_in_transformers/standard_transformers/random_mac.md
              - RandomIP: built_in_transformers/standard_transformers/random_ip.md
              - RandomWord: built_in_transformers/standard_transformers/random_word.md
              - RandomSentence: built_in_transformers/standard_transformers/random_sentence.md
              - RandomParagraph: built_in_transformers/standard_transformers/random_paragraph.md
              - RandomCCType: built_in_transformers/standard_transformers/random_cc_type.md
              - RandomCCNumber: built_in_transformers/standard_transformers/random_cc_number.md
              - RandomCurrency: built_in_transformers/standard_transformers/random_currency.md
              - RandomAmountWithCurrency: built_in_transformers/standard_transformers/random_amount_with_currency.md
              - RandomPhoneNumber: built_in_transformers/standard_transformers/random_phone_number.md
              - RandomTollFreePhoneNumber: built_in_transformers/standard_transformers/random_toll_free_phone_number.md
              - RandomE164PhoneNumber: built_in_transformers/standard_transformers/random_e164_phone_number.md
              - RealAddress: built_in_transformers/standard_transformers/real_address.md
              - RegexpReplace: built_in_transformers/standard_transformers/regexp_replace.md
              - Replace: built_in_transformers/standard_transformers/replace.md
              - SetNull: built_in_transformers/standard_transformers/set_null.md
          - Advanced transformers:
              - built_in_transformers/advanced_transformers/index.md
              - Json: built_in_transformers/advanced_transformers/json.md
              - Template: built_in_transformers/advanced_transformers/template.md
              - TemplateRecord: built_in_transformers/advanced_transformers/template_record.md
              - Custom functions:
                  - built_in_transformers/advanced_transformers/custom_functions/index.md
                  - Core custom functions: built_in_transformers/advanced_transformers/custom_functions/core_functions.md
                  - Faker function: built_in_transformers/advanced_transformers/custom_functions/faker_function.md
      - About: index.md
  - Release notes:
      - Greenmask 0.2.12: release_notes/greenmask_0_2_12.md
      - Greenmask 0.2.11: release_notes/greenmask_0_2_11.md
      - Greenmask 0.2.10: release_notes/greenmask_0_2_10.md
      - Greenmask 0.2.9: release_notes/greenmask_0_2_9.md
      - Greenmask 0.2.8: release_notes/greenmask_0_2_8.md
      - Greenmask 0.2.7: release_notes/greenmask_0_2_7.md
      - Greenmask 0.2.6: release_notes/greenmask_0_2_6.md
      - Greenmask 0.2.5: release_notes/greenmask_0_2_5.md
      - Greenmask 0.2.4: release_notes/greenmask_0_2_4.md
      - Greenmask 0.2.3: release_notes/greenmask_0_2_3.md
      - Greenmask 0.2.2: release_notes/greenmask_0_2_2.md
      - Greenmask 0.2.1: release_notes/greenmask_0_2_1.md
      - Greenmask 0.2.0: release_notes/greenmask_0_2_0.md
      - Greenmask 0.2.0b2: release_notes/greenmask_0_2_0_b2.md
      - Greenmask 0.2.0b1: release_notes/greenmask_0_2_0_b1.md
      - Greenmask 0.1.14: release_notes/greenmask_0_1_14.md
      - Greenmask 0.1.13: release_notes/greenmask_0_1_13.md
      - Greenmask 0.1.12: release_notes/greenmask_0_1_12.md
      - Greenmask 0.1.11: release_notes/greenmask_0_1_11.md
      - Greenmask 0.1.10: release_notes/greenmask_0_1_10.md
      - Greenmask 0.1.9: release_notes/greenmask_0_1_9.md
      - Greenmask 0.1.8: release_notes/greenmask_0_1_8.md
      - Greenmask 0.1.7: release_notes/greenmask_0_1_7.md
      - Greenmask 0.1.6: release_notes/greenmask_0_1_6.md
      - Greenmask 0.1.5: release_notes/greenmask_0_1_5.md
      - Greenmask 0.1.4: release_notes/greenmask_0_1_4.md
      - Greenmask 0.1.3: release_notes/greenmask_0_1_3.md
      - Greenmask 0.1.2: release_notes/greenmask_0_1_2.md
      - Greenmask 0.1.1: release_notes/greenmask_0_1_1.md
      - Greenmask 0.1.0: release_notes/greenmask_0_1_0.md
      - Greenmask 0.1.0 Beta: release_notes/greenmask_0_1_0_beta.md

repo_url: https://github.com/GreenmaskIO/greenmask
repo_name: GreenmaskIO/greenmask
site_url: https://docs.greenmask.io/
copyright: Copyright &copy; 2024 Greenmask


extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-1LGGK7P1GD

    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by using our feedback form
            <iframe 
              src="https://docs.google.com/forms/d/e/1FAIpQLSf6ENCSYImgNa3bNlD1S4ln8AxTVASCt_doTAC2P4Po79ffvA/viewform?embedded=true" 
              width="640" 
              height="447" 
              frameborder="0" 
              marginheight="0" 
              marginwidth="0">Loading…</iframe>


  version:
    provider: mike
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/GreenmaskIO
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/rKBKvDECfd
    - icon: fontawesome/brands/github
      link: https://github.com/GreenmaskIO/greenmask

plugins:
  - social
  - search
  - mike
